"""
Learned-router training.

The learned router uses a tiny regressor that maps a per-node feature vector
to a predicted response latency. Training data is generated by running the
simulator under a teacher policy (typically LeastQueue or LatencyAware) and
collecting tuples (feature_snapshot, observed_latency).

Because the feature snapshot at dispatch time concatenates *all* node features
(6 per node), we slice it back into per-node blocks when training, so a single
model generalises across nodes.

Three model types are supported:
  * "tree"   - sklearn DecisionTreeRegressor (fast, interpretable, no deps
               beyond sklearn).
  * "ridge"  - sklearn Ridge (linear baseline).
  * "mlp"    - a tiny 2-layer PyTorch MLP (if torch is installed).

If sklearn is not installed, a pure-NumPy fallback ridge regressor is used.
"""

from __future__ import annotations

from typing import Optional, Tuple

import numpy as np


class NumpyRidge:
    """Closed-form ridge regression with numpy only.

    This is used as a fallback when sklearn is unavailable. It is plenty fast
    for feature dimensionality in the tens and datasets in the hundreds of
    thousands.
    """

    def __init__(self, alpha: float = 1.0) -> None:
        self.alpha = alpha
        self.w: Optional[np.ndarray] = None
        self.b: float = 0.0

    def fit(self, X: np.ndarray, y: np.ndarray) -> "NumpyRidge":
        Xb = np.hstack([X, np.ones((X.shape[0], 1))])
        d = Xb.shape[1]
        A = Xb.T @ Xb + self.alpha * np.eye(d)
        A[-1, -1] = Xb.T @ Xb[:, -1].sum()  # don't regularise bias
        # Solve
        coef = np.linalg.solve(Xb.T @ Xb + self.alpha * np.eye(d), Xb.T @ y)
        self.w = coef[:-1]
        self.b = float(coef[-1])
        return self

    def predict(self, X: np.ndarray) -> np.ndarray:
        if self.w is None:
            return np.zeros(X.shape[0])
        return X @ self.w + self.b


def _slice_snapshot(snapshot: np.ndarray,
                    n_nodes: int,
                    chosen_idx: int,
                    feat_per_node: int = 6) -> np.ndarray:
    """Extract the feature block for the chosen node from a full snapshot.

    The simulator records features concatenated across all nodes, but training
    should map (one node's features) -> (latency experienced on that node).
    """
    start = chosen_idx * feat_per_node
    end = start + feat_per_node
    return snapshot[start:end]


def build_training_set(records, n_nodes: int,
                       feat_per_node: int = 6
                       ) -> Tuple[np.ndarray, np.ndarray]:
    """Turn raw `RequestRecord`s into (X, y) training arrays."""
    if not records:
        return np.zeros((0, feat_per_node)), np.zeros(0)
    X = np.zeros((len(records), feat_per_node))
    y = np.zeros(len(records))
    for i, r in enumerate(records):
        X[i] = _slice_snapshot(r.snapshot, n_nodes, r.node_id, feat_per_node)
        y[i] = r.latency
    return X, y


def train_model(X: np.ndarray, y: np.ndarray, kind: str = "tree"):
    """Train a regressor. Returns a fitted object with a .predict method."""
    if X.shape[0] == 0:
        raise ValueError("Empty training set")

    kind = kind.lower()
    if kind == "tree":
        try:
            from sklearn.tree import DecisionTreeRegressor
            m = DecisionTreeRegressor(max_depth=10, min_samples_leaf=20,
                                      random_state=0)
            m.fit(X, y)
            return m
        except ImportError:
            pass

    if kind == "ridge":
        try:
            from sklearn.linear_model import Ridge
            m = Ridge(alpha=1.0)
            m.fit(X, y)
            return m
        except ImportError:
            return NumpyRidge(alpha=1.0).fit(X, y)

    if kind == "mlp":
        try:
            import torch
            import torch.nn as nn
            import torch.optim as optim

            d_in = X.shape[1]
            class MLP(nn.Module):
                def __init__(self):
                    super().__init__()
                    self.net = nn.Sequential(
                        nn.Linear(d_in, 32), nn.ReLU(),
                        nn.Linear(32, 16), nn.ReLU(),
                        nn.Linear(16, 1),
                    )
                def forward(self, x):
                    return self.net(x).squeeze(-1)

            torch.manual_seed(0)
            model = MLP()
            opt = optim.Adam(model.parameters(), lr=1e-3)
            Xt = torch.tensor(X, dtype=torch.float32)
            yt = torch.tensor(y, dtype=torch.float32)
            for _ in range(300):
                opt.zero_grad()
                pred = model(Xt)
                loss = ((pred - yt) ** 2).mean()
                loss.backward()
                opt.step()
            model.eval()

            class TorchWrapper:
                def __init__(self, m):
                    self.m = m
                def predict(self, X):
                    import torch as _t
                    with _t.no_grad():
                        return self.m(_t.tensor(X, dtype=_t.float32)).numpy()
            return TorchWrapper(model)
        except ImportError:
            pass

    # Fallback: NumpyRidge
    return NumpyRidge(alpha=1.0).fit(X, y)
